# Generated by Django 5.1.2 on 2024-10-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chemistrycourse_chemistryquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
